# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    - staging
    - trying

jobs:
  - job: Windows

    timeoutInMinutes: 0

    pool:
      vmImage: 'windows-latest'

    strategy:
      matrix:
        Julia 1.4:
          JULIA_VERSION: '1.4'

    steps:
      - checkout: self
        submodules: true

      - powershell: |
          wget https://julialang-s3.julialang.org/bin/winnt/x64/$(JULIA_VERSION)/julia-$(JULIA_VERSION)-latest-win64.exe -OutFile julia-$(JULIA_VERSION)-latest-win64.exe
        displayName: 'Download Julia'

      - powershell: |
          Start-Process -FilePath .\julia-$(JULIA_VERSION)-latest-win64.exe -ArgumentList "/VERYSILENT /DIR=C:\julia-$(JULIA_VERSION)" -NoNewWindow -Wait
        displayName: 'Extract Julia (recent versions)'

      - bash: |
          C:\\julia-$(JULIA_VERSION)\\bin\\julia.exe -e 'using InteractiveUtils; versioninfo()'
          C:\\julia-$(JULIA_VERSION)\\bin\\julia.exe --project=@. -e 'using Pkg; Pkg.instantiate()'
          C:\\julia-$(JULIA_VERSION)\\bin\\julia.exe --project=@. -e 'using Pkg; Pkg.test()'
        displayName: 'Run the tests'
